const data = [
  {
    createdAt: "1997-06-20T15:22:11.266Z",
    text: "Reprehenderit enim cupidatat labore culpa elit amet do incididunt anim amet aute officia. Enim non cupidatat est dolore eu sunt amet nisi eiusmod commodo amet consequat dolore. Do eu nulla nulla aliquip cupidatat exercitation ipsum voluptate labore officia. Sunt fugiat eiusmod aute enim proident consectetur fugiat. Ea est fugiat incididunt deserunt ullamco dolor incididunt irure.",
    isMe: false,
    isRead: false,
    unread: false,
    user: {
      _id: "fcdfa9e4-788e-4178-9c7e-86ae7e2b67c5",
      fullName: "Mcdaniel Carpenter",
      avatar: null,
    },
  },
  {
    createdAt: "1991-05-24T03:39:36.254Z",
    text: "Incididunt laborum aute laboris anim sunt. Voluptate pariatur cupidatat amet eiusmod non amet consectetur elit id aliqua voluptate amet sit id. Eiusmod anim consectetur labore excepteur laboris pariatur ipsum incididunt. Culpa qui reprehenderit mollit id cupidatat sit officia ad incididunt. Reprehenderit aute est laboris ipsum sit elit.",
    isMe: false,
    isRead: false,
    unread: false,
    user: {
      _id: "141f6994-c683-47be-9adf-0c60227d02e7",
      fullName: "Brittany Mack",
      avatar: null,
    },
  },
  {
    createdAt: "1987-02-24T17:30:21.939Z",
    text: "Qui minim in duis occaecat laborum fugiat pariatur occaecat. Velit excepteur qui qui labore incididunt eu officia anim culpa laboris quis aute. Esse et eiusmod pariatur veniam amet amet reprehenderit laborum dolore do cupidatat duis Lorem labore. Enim eu nisi ex ullamco tempor laboris cillum minim laborum velit non. Fugiat pariatur id et voluptate reprehenderit est sint.",
    isMe: true,
    isRead: false,
    unread: true,
    user: {
      _id: "fad33046-ce1f-44f5-aaeb-9fcafbe704f7",
      fullName: "Vance Marquez",
      avatar: null,
    },
  },
  {
    createdAt: "2014-02-08T01:35:58.930Z",
    text: "Ad qui excepteur exercitation veniam nostrud. Ipsum laboris aute voluptate id. Adipisicing sit irure cupidatat ipsum amet quis dolore cupidatat do. Est commodo sunt proident cillum pariatur et. Quis officia voluptate cillum Lorem.",
    isMe: true,
    isRead: true,
    unread: false,
    user: {
      _id: "b020c7b1-67ee-410b-88d6-0c07cc226a3f",
      fullName: "Webb Kline",
      avatar: null,
    },
  },
  {
    createdAt: "2022-12-14T16:22:02.022Z",
    text: "Non in proident quis esse amet qui eu fugiat sint ea ipsum officia id. Lorem minim velit mollit ex do laboris do proident ut duis esse adipisicing id. Nostrud Lorem commodo ut sunt non sit commodo do magna laborum est. Ut Lorem nisi elit ex dolore aliqua anim dolore nostrud sunt est. Anim cillum Lorem et cupidatat id amet duis veniam ipsum.",
    isMe: true,
    isRead: false,
    unread: true,
    user: {
      _id: "66c3ee87-0ddd-4fc5-b91f-4411ffaf3d20",
      fullName: "Winifred Allison",
      avatar: null,
    },
  },
  {
    createdAt: "2006-06-27T20:23:30.046Z",
    text: "Occaecat quis voluptate proident labore. Nulla sunt eu laborum velit tempor qui Lorem cupidatat. Aute amet sunt dolore sunt. Labore ad do nulla consequat. Occaecat sit ex sunt laborum adipisicing anim adipisicing nulla magna.",
    isMe: false,
    isRead: true,
    unread: false,
    user: {
      _id: "16e42d13-d725-484c-bea3-212b04006883",
      fullName: "Ferrell Schwartz",
      avatar: null,
    },
  },
  {
    createdAt: "1984-09-12T02:01:50.417Z",
    text: "Ex do sunt ullamco esse eu laboris. Culpa aute irure deserunt nulla eu et. Aute pariatur magna culpa reprehenderit magna nostrud do eu enim officia. Ipsum commodo pariatur consectetur velit nisi voluptate veniam ullamco reprehenderit dolor. Minim ea cupidatat aliquip sint amet consectetur qui in aute sunt id duis minim.",
    isMe: true,
    isRead: true,
    unread: false,
    user: {
      _id: "a4eb975c-c96c-4e18-a519-fc1ca4fdb878",
      fullName: "Fanny Ortega",
      avatar: null,
    },
  },
  {
    createdAt: "2005-10-09T12:17:39.705Z",
    text: "Qui sit sunt occaecat esse ea laborum elit. Esse amet fugiat non ex nulla voluptate id nostrud. Consequat enim minim do anim. Incididunt ea tempor Lorem id consectetur elit amet tempor nisi commodo. Exercitation esse laborum minim aute sit fugiat dolor est.",
    isMe: false,
    isRead: false,
    unread: false,
    user: {
      _id: "a2e45f79-f0a6-451f-838c-2209cbe63626",
      fullName: "Kennedy Beach",
      avatar: null,
    },
  },
  {
    createdAt: "2015-01-15T20:23:23.916Z",
    text: "Et ut sunt voluptate velit veniam minim aliqua exercitation fugiat minim sit esse magna laborum. Dolor veniam id laboris eiusmod ad fugiat anim est veniam fugiat aliqua deserunt. Deserunt dolor qui aute est reprehenderit sunt minim. Minim magna labore eu quis laboris consectetur nulla. Labore anim nulla adipisicing est reprehenderit Lorem ut.",
    isMe: true,
    isRead: true,
    unread: false,
    user: {
      _id: "96c06848-fd1d-4ab9-8d62-ce667cd4ef15",
      fullName: "Shelley Moore",
      avatar: null,
    },
  },
  {
    createdAt: "1998-05-23T06:35:59.825Z",
    text: "Ex sunt dolor sint aute. Reprehenderit duis adipisicing ad mollit mollit voluptate. Dolore proident officia quis veniam excepteur duis elit dolore voluptate voluptate aliqua cupidatat. Minim incididunt non officia excepteur in Lorem est cillum aute elit nostrud mollit irure. Adipisicing ea irure proident id do excepteur minim sunt nostrud adipisicing consectetur.",
    isMe: false,
    isRead: false,
    unread: false,
    user: {
      _id: "de3ab94d-2418-4574-8abe-3e93826ae445",
      fullName: "Adeline Howe",
      avatar: null,
    },
  },
  {
    createdAt: "2004-04-04T21:21:10.522Z",
    text: "Minim ipsum adipisicing mollit consequat excepteur cupidatat amet. Commodo sunt quis aliqua quis irure et mollit amet. Incididunt amet officia esse officia aliquip duis commodo occaecat. Amet dolore ea eiusmod mollit elit laborum incididunt dolore incididunt ullamco duis amet minim nisi. Cillum nostrud labore nisi anim dolor aliqua.",
    isMe: true,
    isRead: true,
    unread: false,
    user: {
      _id: "44b2c52c-92f6-4ca4-9bf6-87797bff4b69",
      fullName: "Alba Sawyer",
      avatar: null,
    },
  },
  {
    createdAt: "1977-07-26T22:50:39.730Z",
    text: "Veniam cillum deserunt quis nostrud elit id sint. Consectetur et ut exercitation elit qui fugiat et amet aliquip voluptate adipisicing sint ea nisi. Sint enim cillum commodo qui quis mollit ipsum officia pariatur non cillum. Nisi amet consequat qui sint sit. Proident ut Lorem tempor et sit nulla officia velit.",
    isMe: true,
    isRead: false,
    unread: false,
    user: {
      _id: "f1d47cbf-e6e2-4571-8292-b82d57e8723e",
      fullName: "Jeannine Ware",
      avatar: null,
    },
  },
  {
    createdAt: "2007-04-30T20:09:09.199Z",
    text: "Do eu non non eu do sint ea laborum do velit proident fugiat ea. Reprehenderit dolor incididunt cupidatat ullamco proident ad ut aute. Laboris consequat elit magna velit ut. Consectetur ea sunt dolor proident nulla mollit in. Enim elit velit ipsum esse et eu.",
    isMe: true,
    isRead: false,
    unread: false,
    user: {
      _id: "f97248b8-73e1-402c-b1dd-27ab0100818d",
      fullName: "Noreen Barry",
      avatar: null,
    },
  },
  {
    createdAt: "1986-01-07T18:45:51.148Z",
    text: "Incididunt sit incididunt cupidatat ipsum ullamco do velit. Ullamco culpa amet sit ut esse voluptate labore ad et. Culpa nostrud incididunt exercitation eiusmod culpa. Pariatur id nostrud excepteur consectetur irure. Sint adipisicing ex laborum nisi elit est.",
    isMe: true,
    isRead: false,
    unread: false,
    user: {
      _id: "6f623c92-7223-4c32-a966-4e9bf5738e46",
      fullName: "Cathryn Talley",
      avatar: null,
    },
  },
  {
    createdAt: "1995-02-05T02:29:14.266Z",
    text: "Et ea nostrud ex pariatur aute qui. Veniam deserunt irure velit do minim ut cillum officia ex. Quis sit ad non culpa dolor fugiat ipsum cillum et excepteur. Sit cillum anim anim qui laboris non nostrud. Aliquip proident proident sunt ad ex eu Lorem.",
    isMe: true,
    isRead: true,
    unread: false,
    user: {
      _id: "d840497c-dc10-4e1d-901e-8ecdc9160cc7",
      fullName: "Lottie Crawford",
      avatar: null,
    },
  },
];

export default data;
